In [ ]:
import pandas as pd
import numpy as np
d = pd.read_csv("../data/GlobalTemperatures.csv")

In [ ]:
import matplotlib.pyplot as plt
offset = 36
plt.plot(d["LandAverageTemperature"][offset::12])
plt.show()

In [27]:
import matplotlib.cm as cm
dates = d['dt'][offset::12]   # targets a specific month
years = [int(date.split('-')[0]) for date in dates]
tSeq = np.array(d["LandAverageTemperature"][offset::])
tMat = tSeq.reshape(-1,12)
months = np.array(list(range(1,13)))
X, Y = np.meshgrid(months, years)
Z = np.array(tMat)
fig, ax = plt.subplots(subplot_kw={"projection": "3d"})
surf = ax.plot_surface(X, Y, Z, cmap=cm.coolwarm)
plt.show()

In [31]:
fig, ax = plt.subplots()
year_edge = ar([min(yearL), max(yearL)])
w1, w2 = 0.005, -1
temperature_edge = [w1 * year + w2 for year in year_edge]
ax.scatter(yearL, temperature_by_year, label='measurement', c='b', marker='.', s=10)
ax.plot(year_edge, temperature_edge, c='red', marker='.', label='prediction')
ax.legend(loc='lower right')
ax.set_xlabel('Year')
ax.set_ylabel('Temperature')
plt.show()

In [ ]:
plt.plot(years, tMat.mean(axis=1))
plt.plot((1750, 2000), (7, 9.5), color='red')
plt.show()

In [ ]:
plt.plot(years, tMat.mean(axis=1))
# xs = (1750, 2000)
xs = years
a, b = 0.01, -10
ys = [a * x + b for x in xs]
plt.plot(xs, ys, color='red')
plt.show()

In [2]:
import pandas as pd
import numpy as np
from numpy import array as ar
import matplotlib.pyplot as plt

d = pd.read_csv("../data/GlobalTemperatures.csv")

offset = 36   # removes early days to avoid missing data
dateDF = d['dt'][offset::12]   # targets a specific month
temperatureDF = d['LandAverageTemperature'][offset::]
monthL = list(range(1,13))
yearL = ar([int(date.split('-')[0]) for date in dateDF])
temperatureMat = ar(temperatureDF).reshape(-1,12)
tMat = temperatureMat
temperature_by_year = np.mean(temperatureMat, axis=1)
temperature_by_month = np.mean(temperatureMat, axis=0)


In [ ]:
monthL = list(range(1,13))
xs = monthL
a, b, c = - 0.5, 6, -2
w = ar((-0.5, 6, 2))
t_pred_by_month = [a * (x ** 2) + b * x + c for x in xs]
t_by_month = tMat.mean(axis=0)
error = t_by_month - t_pred_by_month
plt.scatter(monthL, t_by_month)
plt.plot(monthL, t_pred_by_month)
plt.show()

In [ ]:
MSE = np.mean(error ** 2)
RMSE = np.sqrt(MSE)
print('RMSE =', RMSE)

RMSE = 13.702487034732128


In [52]:
ev = ar(error).reshape(-1,1)

In [59]:
np.sqrt(ev.T @ ev / len(ev)) == np.sqrt(np.mean(error ** 2))

array([[ True]])

In [1]:
from numpy import array as ar
w = ar((3, 5, 2)).reshape((-1,1))
v = ar((4, 6, 7)).reshape((-1,1))
w.T @ v 


array([[56]])

In [ ]:
years = yearL

In [ ]:
xs = years
ys = temperature_by_year
a, b, c = np.random.random(3)

def predict(x, a, b):
    return a * x + b

# lr = 0.00000001
lr = 1e-9
for _ in range(100):
    for x, y in zip(xs, ys):
        # print('data = ', x, y)
        error = y - predict(x, a, b)
        a += lr * (     )
        b += lr * (     )

plt.plot(xs, ys)
plt.plot(xs, [predict(x, a, b) for x in xs])
plt.show()    

In [ ]:
w = np.array((9, 5, 3))
v = np.array((-2, 4, 1))

In [3]:
w * v

array([-18,  20,   3])

In [ ]:
[x ** 2 for x in range(6)]



30

In [31]:
from functools import reduce

def square(x):
    return x ** 2

def multiply(x, y):
    return x * y 

reduce(multiply, map(square, range(1, 6)))

14400

In [ ]:
x = [1, 2, 5]
w = [4, 3, 2]

def mult(pair):
    return pair[0] * pair[1]
def addition(cmtv, x):
    return cmtv + x

reduce(addition, map(mult, zip(x, w)))

20

In [28]:
from numpy import array as ar
A = ar([[8, 5],
        [7, 3]])
B = ar([[10,   20],
        [100, 200]])

In [29]:
(A @ B).T

array([[ 580,  370],
       [1160,  740]])

In [31]:
A.T @ B.T

array([[ 220, 2200],
       [ 110, 1100]])

In [27]:
A @ B

NameError: name 'A' is not defined

In [4]:
import matplotlib.pyplot as plt
import numpy as np
from numpy import array as ar
import pandas as pd
import matplotlib.cm as cm

df = pd.read_csv('concrete_data.csv')

strength = df['Strength']
cement = df['Cement']
water = df['Water']
sp = df['Superplasticizer']
fineness = df['Fine Aggregate']
age = df['Age']

In [ ]:
# gradient descent
from numpy import array as ar
import pandas as pd
df = pd.read_csv('concrete_data.csv')
strength = df['Strength']
cement = df['Cement']
water = df['Water']
x1r, x2r, yr = cement, water, strength
X = ar([x1r, x2r, np.ones(len(x1r))]).T
y = ar(yr).reshape(-1, 1)

lr = 1e-8
epochNum = 10
trialNum = 10

def prediction(X, w):
    return X @ w

rmse_L = []
for _ in range(trialNum):
    w = np.random.random(X.shape[1]).reshape(-1, 1)
    for epochID in range(epochNum):
        error = y - prediction(X, w)
        w += lr * (error.T @ X).T

    y_pred = prediction(X, w)
    rmse = np.sqrt(((y - y_pred) ** 2).mean())
    print('RMSE =', rmse)
    rmse_L.append(rmse)

RMSE = 18.30852929998207
RMSE = 18.451995392785737
RMSE = 18.29877553106281
RMSE = 18.29992791564639
RMSE = 18.336528952544032
RMSE = 18.32866975959566
RMSE = 18.40466096761478
RMSE = 18.368603037747835
RMSE = 18.457176049116836
RMSE = 18.37775771854227


In [49]:
from numpy import array as ar
import pandas as pd
df = pd.read_csv('concrete_data.csv')
strength = df['Strength']
cement = df['Cement']
water = df['Water']
x1r, x2r, yr = cement, water, strength
X = ar([x1r, x2r, x2r + x1r, np.ones(len(x1r))]).T
y = ar(yr).reshape(-1, 1)
# w = np.linalg.solve(X.T @ X, X.T @ y)
w = np.linalg.inv(X.T @ X) @ X.T @ y
y_pred = X @ w
rmse = np.sqrt(((y - y_pred) ** 2).mean())
print('RMSE =', rmse)

RMSE = 13.897244330807025


In [44]:
A = ar([[5, 2],
        [4, 4]])
b = ar([5, 10]).reshape(-1,1)
np.linalg.inv(A)

array([[ 0.33333333, -0.16666667],
       [-0.33333333,  0.41666667]])

In [26]:
X.T @ y

array([[11267333.595],
       [ 6592151.307],
       [   36892.5  ]])

In [42]:
from numpy import array as ar
A = ar([[1, 2],
        [5, 10]])
B = np.linalg.inv(A)
A @ B

array([[0., 0.],
       [0., 1.]])

In [75]:
a = ar([1, 2, 3, 4])
b = ar([3, 4, 5, 6])
c = ar([9, 8, 1, 9])
A = ar([a - b, b - a, b, a])
np.linalg.matrix_rank(A)

np.int64(2)

In [74]:
A.shape

(4, 4)